### ISSUE TITLE
checkpoint/restore support not available

### ISSUE THREAD

**Issue by jguionnet** [MartinHeinz/kubeadm-vagrant-playground#1]
Hi 

Thank you so much for providing this auto-configuration to play with this great new feature. 

I am on an intel based mac, using virtual box and I am hitting the following issue:

When I tried to checkpoint, I got the following error 
`checkpointing of default/webserver/webserver failed (rpc error: code = Unknown desc = checkpoint/restore support not available)`

```sh
curl -sk -X POST  "https://localhost:10250/checkpoint/default/webserver/webserver"   --key /etc/kubernetes/pki/apiserver-kubelet-client.key   --cacert /etc/kubernetes/pki/ca.crt   --cert /etc/kubernetes/pki/apiserver-kubelet-client.crt
```

`checkpointing of default/webserver/webserver failed (rpc error: code = Unknown desc = checkpoint/restore support not available)`

I checked that the feature gate is enabled in the `/etc/kubernetes/manifest` directory tree

```sh
root@kubemaster:/etc/kubernetes/manifests# grep -i feature *.yaml
kube-apiserver.yaml:    - --feature-gates=ContainerCheckpoint=true
kube-controller-manager.yaml:    - --feature-gates=ContainerCheckpoint=true
kube-scheduler.yaml:    - --feature-gates=ContainerCheckpoint=true
```

Thanks

Jerome

**Comment by MartinHeinz** [comment]
Hi Jerome, it looks like the CRI doesn't support checkpointing. Are you using the `container-checkpoint-api` branch?

**Comment by jguionnet** [comment]
No, I miss that part... retrying, and I will let you know. Thanks for the quick turn around!

**Comment by jguionnet** [comment]
It works! 

I add to do the following changes though:

in `kube-tools.sh`, add the version for some components as else it was fetching the latest, 1.26, which was incompatible with other
`apt-get install -y kubelet=1.25.0-00 kubeadm=1.25.0-00 kubectl=1.25.0-00`

The error was:
```
    kubemaster: error execution phase preflight: [preflight] Some fatal errors occurred:
    kubemaster: 	[ERROR KubeletVersion]: the kubelet version is higher than the control plane version. This is not a supported version skew and may lead to a malfunctional cluster. Kubelet version: "1.26.0" Control plane version: "1.25.0"
```

Minor: I add to install `docker` and `buildah` during the restore phase 

I can submit a PR for the version changes if needed. I wonder if other version dependencies like these should also be changed.

Thanks a lot again.

Jerome

**Comment by jguionnet** [comment]
I played more with it, and I was able to checkpoint and restore a simple python flask app incrementing a global counter. The restored pod was with the in memory state  (ie increased counter). It is cool. 

I then tried to use it for one of our java apps, which is pretty complicated, and I could not dump it as I got this error 
```
checkpointing of default/cm/cm failed (rpc error: code = Unknown desc = failed to checkpoint container e22d113516ffb79b20f9a4dfd13aff60fb00d5d72efd9d453e4aa5554c9b516d: running "/usr/sbin/runc" ["checkpoint" "--image-path" "/var/lib/containers/storage/overlay-containers/e22d113516ffb79b20f9a4dfd13aff60fb00d5d72efd9d453e4aa5554c9b516d/userdata/checkpoint" "--work-path" "/var/lib/containers/storage/overlay-containers/e22d113516ffb79b20f9a4dfd13aff60fb00d5d72efd9d453e4aa5554c9b516d/userdata" "--leave-running" "e22d113516ffb79b20f9a4dfd13aff60fb00d5d72efd9d453e4aa5554c9b516d"] failed: `/usr/sbin/runc --root /run/runc --systemd-cgroup checkpoint --image-path /var/lib/containers/storage/overlay-containers/e22d113516ffb79b20f9a4dfd13aff60fb00d5d72efd9d453e4aa5554c9b516d/userdata/checkpoint --work-path /var/lib/containers/storage/overlay-containers/e22d113516ffb79b20f9a4dfd13aff60fb00d5d72efd9d453e4aa5554c9b516d/userdata --leave-running e22d113516ffb79b20f9a4dfd13aff60fb00d5d72efd9d453e4aa5554c9b516d` failed: time="2022-12-10T04:29:44Z" level=error msg="criu failed: type NOTIFY errno 0\nlog file: /var/lib/containers/storage/overlay-containers/e22d113516ffb79b20f9a4dfd13aff60fb00d5d72efd9d453e4aa5554c9b516d/userdata/dump.log"
```
which in the `dump.log` shows as:
`10.242437) Error (criu/file-lock.c:110): Some file locks are hold by dumping tasks! You can try --file-locks to dump them.`

I glanced at the `/etc/crio/crio.conf` but I could not figure out how to pass this option. If you know the answer I would appreciate it if you can share but if not, do not worry, I will investigate further.

**Comment by MartinHeinz** [comment]
Good catch regarding the `apt-get install ...`, feel free to submit PR for it if you want. I can also fix it later.

As for the Java issue - I haven't encountered that - quick Google search found this: https://criu.org/What_cannot_be_checkpointed - Looks like that container cannot be checkpointed without the `--file-locks` option.

**Comment by jguionnet** [comment]
I found that, and the solution for your configuration is to add
`echo "file-locks" > /etc/criu/runc.conf` 

So I added the following in `crio.sh`
```bash
mkdir /etc/criu
echo "file-locks" > /etc/criu/runc.conf
```
